name: Publish Docker image

on:
    push:
        tags:
            - "v*.*.*"

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker images
        run : |
          make docker-build VERSION=${{ github.ref_name }}
          make docker-build

      - name: Publish Docker images
        run : |
          make docker-push VERSION=${{ github.ref_name }}
          make docker-push
