name: pypi
on:
  workflow_run:
    workflows: 
      - build
    branches:
#      - main
      - dev
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Build package
        run: |
          make build

      - name: Publish package to Test PyPI
        if: ${{ github.ref == 'refs/head/dev' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish package to PyPI
        if: ${{ github.ref == 'refs/head/main' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
